### ISSUE TITLE
x-if-else should be x-else-if

### ISSUE THREAD

**Issue by mwxxhdb** [kirakiray/ofa-v4-docs#41]
![image](https://github.com/ofajs/ofa-v4-docs/assets/8121121/83a8c833-3e05-4e4f-93af-f4ac2195b7b2)

**Comment by kirakiray** [comment]
😂 Yes, the document is wrong, thank you for reminding me

**Comment by kirakiray** [comment]
The official website has been corrected now, thank you for your feedback 🙏
